[build]
  publish = "_site"
  command = "npm run build"
  functions = "netlify/functions"

[[redirects]]
from = "https://teej.netlify.app/*"
to = "https://tj.ie/:splat"

[[redirects]]
from = "/feed/feed.xml"
to = "/index.xml"

[[redirects]]
from = "/journal/"
to = "/"

[[redirects]]
from = "/journal/*"
to = "/:splat"
