[build]
  publish = "_site"
  command = "npm run build"

[[redirects]]
from = "https://teej.netlify.com/*"
to = "https://tj.ie/:splat"

[[redirects]]
from = "https://tj.ie/feed/feed.xml"
to = "https://tj.ie/index.xml"
